### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by MinecraftPlayer523** [MSWI-Team/MSWI#1]
# ToDo
#### Basic Server Interface
- [ ] Id, Name, Version, Description
- [ ] Server Vanilla Updater
- [ ] Server Vanilla Runner

#### Server Configuration
- [ ] File Manager
- [ ] Configuration
- [ ] Plugin Manager

#### Authentification
- [ ] Simple Login
- [ ] Users, Groups, Roles
- [ ] Permissions
#### Event Matrix
- [ ] Add Events
- [ ] Add Event Matrix

#### Restructure Project
- [ ] Restructure Project
- [ ] Plugins
- [ ] Updater
- [ ] Error Catcher
- [ ] Restarter

### Server Statistics
- [ ] Ram, Cpu Ussage
- [ ] User statistic

#### Support for other platforms
- [ ] Add basic additons
- [ ] Add Craftbukkit/Spigot/Paper Support
- [ ] Add Forge Support
- [ ] Plugin/Mods downloader
